apiVersion: apps/v1
kind: Deployment

metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: "goserver"
        image: "oalessandrovpa/hello-go:v5.1"

        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 3
          failureThreshold: 10

        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 3
          failureThreshold: 1
          # initialDelaySeconds: 10

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1
          # initialDelaySeconds: 15

        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
        volumeMounts:
          - mountPath: "/go/techs"
            name: config
      volumes:
        - name: config
          configMap:
            name: goserver-techs
            items:
              - key: techs
                path: "techs.txt"
        # env:
        #   - name: NAME
        #     valueFrom:
        #       configMapKeyRef:
        #         name: goserver-env
        #         key: NAME
        #   - name: AGE
        #     valueFrom:
        #       configMapKeyRef:
        #         name: goserver-env
        #         key: AGE