apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: goserver
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30